### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by hn957** [shuyifan1024/EC601_Twitter_API#1]
I think you did a great job on the twitter API. The ability to allow the user to input keywords and limit is a great. However, I can't find any information on your work on the Google NLP or the unit test.

**Comment by shuyifan1024** [comment]
Hello, thank you for your comment. My Google NLP is in another folder on GitHub.  You can see this on my home page.
This is my Google NLP link. 
https://github.com/shuyifan1024/EC601-Google-NLP-API.git
Could you check it again?  The grade of this course is very important to me.  I'm very sorry for your time. Thank you very much sincerely!

**Comment by hn957** [comment]
Google NLP is in another repo. 
Issue solved.
